# Logistic regression

## Reading the joined data from the local folder

```{R}
# reading the data from a local folder
library(readr)
alc <- read.csv("data/joined_alc_data.csv")

```

## Exploration of the data
Original data source: https://www.archive.ics.uci.edu/dataset/320/student+performance

The data consist of information on secondary education student performance in Portugal. The data is joined from two data sets 

```{R}
# Exploration of the data variables

str(alc)
colnames(alc)

```

* The data set has 370 observations and 35 variables. 
  + There are character, intgrer and logical variables in the data
  + The variables give information on, e.g.. students background, school performance in maths and Portuguese (test scores 'G1', 'G2', and final grade 'G3') and alcohol consumption
* The students are between 15-22 years of age.

The dependent binary variable 'high_use' is when the mean of 'Dalc' and 'Walc' > 2
* 'Dalc' - workday alcohol consumption numeric: from 1 - very low to 5 - very high)
* 'Walc' - weekend alcohol consumption (numeric: from 1 - very low to 5 - very high)

In this analysis we will use logistic regression to test the relationship of four chosen background variables with the binary dependent variable 'high_use'.

## Choosing the variables 

* The variables:
  1. 'school' student's school (binary: 'GP' - Gabriel Pereira or 'MS' - Mousinho da Silveira) 
  2. 'famrel' quality of family relationships (numeric: from 1 - very bad to 5 - excellent)
  3. 'absences' number of school absences (numeric: from 0 to 93)
  4. 'G3' final grade (numeric: from 0 to 20, output target)

## Hypothesis:

The hypothesis for the variables: 

* 'school' is interesting to look at as it could affect the model if the two different schools have socioeconomically different student base. The hypothesis here would be that there is no effect
* 'famrel' better family relationship would indicate less alcohol consumption, as maybe they teens would be then more inclined to spend time wiht their families which would include less drinking
* 'absences' could have a positive correlation with the alcohol consumption.
* 'G3' the final score could be negatively correlated with high use

## Exploration of the variable distributions

To see any potential differences we use boxplots for the continuous variables 'absences' and 'G3'.

```{R}
library(ggplot2)

```


```{R}

```
The tables are mainly useful for 'school' which is a binary variable, others get difficult to interpret

```{R}


```

## Statistical analysis